import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";

import "./globals.css";
import Header from "@/components/ui/header";

const roboto = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Interactive AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={roboto.className}>
      <body>{children}</body>
    </html>
  );
}
